[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Robots-Tag = "noarchive"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
